package jpdftweak.tabs.watermark.optionpanels;

import java.util.ArrayList;
import java.util.List;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import jpdftweak.tabs.watermark.WatermarkStyle;

/**
 *
 * @author Vasilis Naskos
 */
public class WatermarkBatesPanel extends javax.swing.JPanel {

	private WatermarkStyle style;
	private List<Integer> pages;

	/**
	 * Creates new form WatermarkBatesPanel
	 */
	public WatermarkBatesPanel() {
		initComponents();

		pages = new ArrayList<Integer>();

		prefixField.getDocument().addDocumentListener(new DocumentListener() {

			
			public void insertUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesPrefix(prefixField.getText());
			}

			
			public void removeUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesPrefix(prefixField.getText());
			}

			
			public void changedUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesPrefix(prefixField.getText());
			}
		});

		suffixField.getDocument().addDocumentListener(new DocumentListener() {

			
			public void insertUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesSuffix(suffixField.getText());
			}

			
			public void removeUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesSuffix(suffixField.getText());
			}

			
			public void changedUpdate(DocumentEvent e) {
				if (style != null)
					style.setBatesSuffix(suffixField.getText());
			}
		});

		pagesField.getDocument().addDocumentListener(new DocumentListener() {

			
			public void insertUpdate(DocumentEvent e) {
				changed();
			}

			
			public void removeUpdate(DocumentEvent e) {
				changed();
			}

			
			public void changedUpdate(DocumentEvent e) {
				changed();
			}

			private void changed() {
				if (style == null) {
					return;
				}

				style.setBatesPages(pagesField.getText());
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		startWithSpinner = new javax.swing.JSpinner();
		stepSpinner = new javax.swing.JSpinner();
		repeatForSpinner = new javax.swing.JSpinner();
		zeroPaddingSpinner = new javax.swing.JSpinner();
		prefixField = new javax.swing.JTextField();
		suffixField = new javax.swing.JTextField();
		applyToComboBox = new javax.swing.JComboBox();
		jLabel8 = new javax.swing.JLabel();
		pagesField = new javax.swing.JTextField();

		setBorder(javax.swing.BorderFactory.createTitledBorder("Bates Numbering"));

		jLabel1.setText("Start with:");

		jLabel2.setText("Step:");

		jLabel3.setText("Repeat For:");

		jLabel4.setText("Zero padding:");

		jLabel5.setText("Prefix:");

		jLabel6.setText("Suffix:");

		jLabel7.setText("Apply to:");

		startWithSpinner
		.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
		startWithSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				startWithSpinnerStateChanged(evt);
			}
		});

		stepSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
		stepSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				stepSpinnerStateChanged(evt);
			}
		});

		repeatForSpinner.setModel(
				new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
		repeatForSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				repeatForSpinnerStateChanged(evt);
			}
		});

		zeroPaddingSpinner.setModel(
				new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
		zeroPaddingSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				zeroPaddingSpinnerStateChanged(evt);
			}
		});

		applyToComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "All", "Odd", "Even", "Image Files", "PDF Files", "Only:", "Exlude:" }));
		applyToComboBox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				applyToComboBoxItemStateChanged(evt);
			}
		});

		jLabel8.setText("Pages:");

		pagesField.setEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(startWithSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(stepSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(repeatForSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(zeroPaddingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(prefixField))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel6)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(suffixField))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(applyToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pagesField)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7 });

		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(startWithSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(stepSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(repeatForSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(zeroPaddingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(prefixField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6)
						.addComponent(suffixField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7)
						.addComponent(applyToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8)
						.addComponent(pagesField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void startWithSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_startWithSpinnerStateChanged
		int value = Integer.parseInt(startWithSpinner.getValue().toString());
		style.setBatesStartWith(value);
	}// GEN-LAST:event_startWithSpinnerStateChanged

	private void stepSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_stepSpinnerStateChanged
		int value = Integer.parseInt(stepSpinner.getValue().toString());
		style.setBatesStep(value);
	}// GEN-LAST:event_stepSpinnerStateChanged

	private void repeatForSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_repeatForSpinnerStateChanged
		int value = Integer.parseInt(repeatForSpinner.getValue().toString());
		style.setBatesRepeatFor(value);
	}// GEN-LAST:event_repeatForSpinnerStateChanged

	private void zeroPaddingSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_zeroPaddingSpinnerStateChanged
		int value = Integer.parseInt(zeroPaddingSpinner.getValue().toString());
		style.setBatesZeroPadding(value);
	}// GEN-LAST:event_zeroPaddingSpinnerStateChanged

	private void applyToComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_applyToComboBoxItemStateChanged
		int value = applyToComboBox.getSelectedIndex();
		style.setBatesApplyTo(value);
		if (value == 5 || value == 6) {
			pagesField.setEnabled(true);
		} else {
			pagesField.setEnabled(false);
		}
	}// GEN-LAST:event_applyToComboBoxItemStateChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox applyToComboBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JTextField pagesField;
	private javax.swing.JTextField prefixField;
	private javax.swing.JSpinner repeatForSpinner;
	private javax.swing.JSpinner startWithSpinner;
	private javax.swing.JSpinner stepSpinner;
	private javax.swing.JTextField suffixField;
	private javax.swing.JSpinner zeroPaddingSpinner;
	// End of variables declaration//GEN-END:variables

	public void setStyle(WatermarkStyle style) {
		this.style = style;

		startWithSpinner.setValue(style.getBatesStartWith());
		stepSpinner.setValue(style.getBatesStep());
		repeatForSpinner.setValue(style.getBatesRepeatFor());
		zeroPaddingSpinner.setValue(style.getBatesZeroPadding());
		prefixField.setText(style.getBatesPrefix());
		suffixField.setText(style.getBatesSuffix());
		applyToComboBox.setSelectedIndex(style.getBatesApplyTo());
		pagesField.setText(style.getBatesPages());
	}

}
